// app/semi-anon/page.tsx
import type { Metadata } from "next";
import { Header } from "@/components/shell/header";
import { Footer } from "@/components/shell/footer";
import { SemiAnonContent } from "@/components/mado/semi-anon-content";

export const metadata: Metadata = { title: "半匿名の仕組み" };

export default function SemiAnonPage() {
  return (
    <div className="flex flex-col min-h-dvh">
      <Header />
      <main className="flex-1">
        <SemiAnonContent />
      </main>
      <Footer />
    </div>
  );
}

// sveltekit-web/src/routes/semi-anon/+page.svelte
<script lang="ts">
  import type { PageData } from "./$types";
  import Header from "$lib/components/shell/Header.svelte";
  import Footer from "$lib/components/shell/Footer.svelte";
  import SemiAnonContent from "$lib/components/mado/SemiAnonContent.svelte";

  let { data }: { data: PageData } = $props();
</script>

<svelte:head><title>半匿名の仕組み | Mado</title></svelte:head>

<div class="flex flex-col min-h-dvh">
  <Header session={data.session} />
  <main class="flex-1"><SemiAnonContent /></main>
  <Footer />
</div>
