// components/mado/block-button.tsx
"use client";

import * as React from "react";
import { Ban, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";

interface BlockButtonProps {
  senderDid: string;
}

type State = "idle" | "confirm" | "submitting" | "done" | "unblocking" | "error";

export function BlockButton({ senderDid }: BlockButtonProps) {
  const [state, setState] = React.useState<State>("idle");

  const handleClick = async () => {
    if (state === "idle" || state === "error") {
      setState("confirm");
      return;
    }

    if (state === "confirm") {
      setState("submitting");
      try {
        const res = await fetch("/api/blocks/create", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ senderDid }),
        });
        if (!res.ok) {
          setState("error");
        } else {
          setState("done");
        }
      } catch {
        setState("error");
      }
    }
  };

  const handleUnblock = async () => {
    setState("unblocking");
    try {
      const res = await fetch("/api/blocks/remove", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ senderDid }),
      });
      if (!res.ok) {
        setState("done");
      } else {
        setState("idle");
      }
    } catch {
      setState("done");
    }
  };

  if (state === "done" || state === "unblocking") {
    return (
      <div className="flex items-center gap-2 flex-1 sm:flex-none">
        <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm text-muted">
          <CheckCircle2 size={14} />
          ブロックしました
        </div>
        <Button
          variant="ghost"
          size="sm"
          loading={state === "unblocking"}
          onClick={handleUnblock}
          className="text-xs text-subtle"
        >
          解除
        </Button>
      </div>
    );
  }

  return (
    <Button
      variant={state === "confirm" ? "destructive" : "outline"}
      size="sm"
      leftIcon={<Ban size={14} />}
      className="flex-1 sm:flex-none"
      loading={state === "submitting"}
      onClick={handleClick}
    >
      {state === "confirm" ? "本当にブロックしますか？" : state === "error" ? "再試行" : "送信者をブロック"}
    </Button>
  );
}

// src/lib/components/mado/BlockButton.svelte
<script lang="ts">
  import { Ban, CheckCircle2 } from "lucide-svelte";
  import Button from "$lib/components/ui/Button.svelte";

  interface Props {
    senderDid: string;
  }

  let { senderDid }: Props = $props();

  type State = "idle" | "confirm" | "submitting" | "done" | "unblocking" | "error";
  let state = $state<State>("idle");

  async function handleClick() {
    if (state === "idle" || state === "error") {
      state = "confirm";
      return;
    }

    if (state === "confirm") {
      state = "submitting";
      try {
        const res = await fetch("/api/blocks/create", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ senderDid }),
        });
        state = res.ok ? "done" : "error";
      } catch {
        state = "error";
      }
    }
  }

  async function handleUnblock() {
    state = "unblocking";
    try {
      const res = await fetch("/api/blocks/remove", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ senderDid }),
      });
      state = res.ok ? "idle" : "done";
    } catch {
      state = "done";
    }
  }
</script>

{#if state === "done" || state === "unblocking"}
  <div class="flex items-center gap-2 flex-1 sm:flex-none">
    <div class="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm text-muted">
      <CheckCircle2 size={14} />
      ブロックしました
    </div>
    <Button
      variant="ghost"
      size="sm"
      loading={state === "unblocking"}
      onclick={handleUnblock}
      class="text-xs text-subtle"
    >
      解除
    </Button>
  </div>
{:else}
  <Button
    variant={state === "confirm" ? "destructive" : "outline"}
    size="sm"
    class="flex-1 sm:flex-none"
    loading={state === "submitting"}
    onclick={handleClick}
  >
    {#snippet leftIcon()}<Ban size={14} />{/snippet}
    {state === "confirm" ? "本当にブロックしますか？" : state === "error" ? "再試行" : "送信者をブロック"}
  </Button>
{/if}
