// src/lib/components/shell/Sidebar.svelte
<script lang="ts">
  import { LayoutDashboard, Inbox, Send, User } from "lucide-svelte";
  import InfoNav from "./InfoNav.svelte";
  import UserCard from "./UserCard.svelte";
  import type { AppSession } from "$lib/store.js";

  interface Props {
    session: AppSession;
    onNavigate?: () => void;
  }

  let { session, onNavigate }: Props = $props();

  const navItems = $derived([
    { href: "/dashboard", icon: LayoutDashboard, label: "ホーム" },
    { href: `/@${session.handle}`, icon: User, label: "マイページ" },
    { href: "/receive", icon: Inbox, label: "受信トレイ" },
    { href: "/sent", icon: Send, label: "送信トレイ" },
  ]);
</script>

<!-- Logo -->
<div class="h-16 px-5 flex items-center gap-2 shrink-0 border-b border-border">
  <a href="/dashboard" class="flex items-center gap-2" onclick={onNavigate}>
    <img src="/mado-logo.svg" alt="Mado" class="w-8 h-8" />
    <span class="font-bold text-base text-primary">Mado</span>
  </a>
</div>

<!-- Navigation -->
<nav class="flex-1 py-4 px-3 overflow-y-auto">
  <div class="flex flex-col gap-0.5">
    {#each navItems as item}
      <a
        href={item.href}
        onclick={onNavigate}
        class="flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all duration-200 text-muted"
      >
        <item.icon size={17} class="shrink-0" />
        {item.label}
      </a>
    {/each}
    <InfoNav {onNavigate} />
  </div>
</nav>

<!-- User info -->
<UserCard {session} />

// components/shell/dashboard/sidebar.tsx
"use client";

import Link from "next/link";
import { LayoutDashboard, MessageSquare, Inbox, Send } from "lucide-react";
import { InfoNav } from "@/components/shell/info-nav";
import { UserCard } from "./user-card";

const navItems = [
  { href: "/dashboard", icon: LayoutDashboard, label: "ダッシュボード" },
  { href: "/dashboard/boxes", icon: MessageSquare, label: "質問箱" },
  { href: "/dashboard/questions", icon: Inbox, label: "受信トレイ" },
  { href: "/dashboard/sent", icon: Send, label: "送信トレイ" },
];

interface SidebarProps {
  session: {
    handle: string;
    displayName?: string;
    avatar?: string;
  };
  onNavigate?: () => void;
}

{/* *** ダッシュボードのサイドバー *** */}
export function Sidebar({ session, onNavigate }: SidebarProps) {
  return (
    <>
      {/* ロゴ */}
      <div className="h-16 px-5 flex items-center gap-2 shrink-0 border-b border-border">
        <Link href="/dashboard" className="flex items-center gap-2" onClick={onNavigate}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/mado-logo.svg" alt="Mado" className="w-8 h-8" />
          <span className="font-bold text-base text-primary">Mado</span>
        </Link>
      </div>

      {/* ナビゲーション */}
      <nav className="flex-1 py-4 px-3 overflow-y-auto">
        <div className="flex flex-col gap-0.5">
          {navItems.map((item) => (
            <Link
              key={item.href}
              href={item.href}
              onClick={onNavigate}
              className="flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all duration-200 text-muted"
            >
              <item.icon size={17} className="shrink-0" />
              {item.label}
            </Link>
          ))}
          <InfoNav onNavigate={onNavigate} />
        </div>
      </nav>

      {/* ユーザー情報 */}
      <UserCard session={session} />
    </>
  );
}
