// components/ui/input.tsx
"use client";

import * as React from "react";
import { cn } from "@/lib/utils";

export interface InputProps
  extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
  helper?: string;
  leftAddon?: React.ReactNode;
  rightAddon?: React.ReactNode;
}

export const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, label, error, helper, leftAddon, rightAddon, id, ...props }, ref) => {
    const inputId = id ?? (label ? label.toLowerCase().replace(/\s+/g, "-") : undefined);

    return (
      <div className="flex flex-col gap-1.5 w-full">
        {label && (
          <label htmlFor={inputId} className="text-sm font-medium text-muted">
            {label}
          </label>
        )}
        <div className="relative flex items-center">
          {leftAddon && (
            <div className="absolute left-3 flex items-center pointer-events-none text-subtle">
              {leftAddon}
            </div>
          )}
          <input
            ref={ref}
            id={inputId}
            className={cn(
              "w-full rounded-lg px-4 py-3 text-sm transition-all duration-200",
              "focus:outline-none focus:ring-2",
              "placeholder:opacity-50",
              "bg-elevated text-primary",
              error
                ? "border border-red-600/40 ring-1 ring-red-500/50 focus:ring-red-500/60"
                : "border border-border focus:ring-blue-500/40",
              leftAddon && "pl-10",
              rightAddon && "pr-10",
              className
            )}
            {...props}
          />
          {rightAddon && (
            <div className="absolute right-3 flex items-center text-subtle">
              {rightAddon}
            </div>
          )}
        </div>
        {error && <p className="text-xs text-error">{error}</p>}
        {helper && !error && <p className="text-xs text-subtle">{helper}</p>}
      </div>
    );
  }
);

Input.displayName = "Input";

// sveltekit-web/src/lib/components/ui/Input.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLInputAttributes } from "svelte/elements";
  import { cn } from "$lib/utils.js";

  interface Props extends Omit<HTMLInputAttributes, "class"> {
    label?: string;
    error?: string;
    helper?: string;
    class?: string;
    leftAddon?: Snippet;
    rightAddon?: Snippet;
  }

  let {
    label,
    error,
    helper,
    class: className = "",
    leftAddon,
    rightAddon,
    id,
    value = $bindable(""),
    ...restProps
  }: Props = $props();

  const inputId = $derived(id ?? (label ? label.toLowerCase().replace(/\s+/g, "-") : undefined));
</script>

<div class="flex flex-col gap-1.5 w-full">
  {#if label}
    <label for={inputId} class="text-sm font-medium text-muted">{label}</label>
  {/if}
  <div class="relative flex items-center">
    {#if leftAddon}
      <div class="absolute left-3 flex items-center pointer-events-none text-subtle">
        {@render leftAddon()}
      </div>
    {/if}
    <input
      id={inputId}
      bind:value
      class={cn(
        "w-full rounded-lg px-4 py-3 text-sm transition-all duration-200",
        "focus:outline-none focus:ring-2",
        "placeholder:opacity-50",
        "bg-elevated text-primary",
        error
          ? "border border-red-600/40 ring-1 ring-red-500/50 focus:ring-red-500/60"
          : "border border-border focus:ring-blue-500/40",
        leftAddon && "pl-10",
        rightAddon && "pr-10",
        className
      )}
      {...restProps}
    />
    {#if rightAddon}
      <div class="absolute right-3 flex items-center text-subtle">
        {@render rightAddon()}
      </div>
    {/if}
  </div>
  {#if error}
    <p class="text-xs text-error">{error}</p>
  {:else if helper}
    <p class="text-xs text-subtle">{helper}</p>
  {/if}
</div>
