// app/dashboard/sent/page.tsx
import type { Metadata } from "next";
import { Send } from "lucide-react";
import { requireSession } from "@/lib/auth";
import { getRedis, Keys } from "@/lib/redis";
import { getAnswersByOwner } from "@/lib/atproto";
import { SentList } from "@/components/mado/sent-list";
import type { SentRef } from "@/types";

export const metadata: Metadata = { title: "送信トレイ" };

export default async function SentPage() {
  const session = await requireSession();
  const redis = getRedis();

  const sentRefs = await redis.lrange<SentRef>(Keys.sent(session.did), 0, -1);
  const readMembers = await redis.smembers(Keys.sentRead(session.did));
  const readSet = new Set(readMembers as string[]);

  const uniqueOwners = [...new Set(sentRefs.map((r) => r.ownerDid))];
  const answerMapEntries = await Promise.all(
    uniqueOwners.map(async (ownerDid) => {
      const map = await getAnswersByOwner(ownerDid);
      return { ownerDid, map };
    })
  );
  const allAnswers = new Map(
    answerMapEntries.flatMap(({ map }) => [...map.entries()])
  );

  const items = sentRefs.map((ref) => {
    const koeUri = `at://${ref.ownerDid}/blue.mado.koe/${ref.koeRkey}`;
    const answers = allAnswers.get(koeUri) ?? [];
    const isRead = readSet.has(`${ref.ownerDid}:${ref.koeRkey}`);
    return { ref, koeUri, answers, isRead };
  });

  return (
    <div className="px-6 py-8 max-w-2xl mx-auto">
      {/* Header */}
      <div className="flex items-center gap-3 mb-8">
        <div className="w-9 h-9 rounded-xl flex items-center justify-center bg-accent-light">
          <Send size={17} className="text-accent" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-primary">送信トレイ</h1>
          <p className="text-xs text-muted">あなたが送った質問と返信</p>
        </div>
      </div>

      <SentList items={items} />
    </div>
  );
}

// src/routes/(app)/sent/+page.svelte
<script lang="ts">
  import { Send } from "lucide-svelte";
  import SentList from "$lib/components/mado/SentList.svelte";
  import type { PageData } from "./$types";

  let { data }: { data: PageData } = $props();
</script>

<svelte:head>
  <title>送信トレイ | Mado</title>
</svelte:head>

<div class="px-6 py-8 max-w-2xl mx-auto">
  <div class="flex items-center gap-3 mb-8">
    <div class="w-9 h-9 rounded-xl flex items-center justify-center bg-accent-light">
      <Send size={17} class="text-accent" />
    </div>
    <div>
      <h1 class="text-xl font-bold text-primary">送信トレイ</h1>
      <p class="text-xs text-muted">あなたが送った質問と返信</p>
    </div>
  </div>

  <SentList items={data.items} />
</div>
