// sveltekit-web/src/routes/guide/+page.svelte
<script lang="ts">
  import type { PageData } from "./$types";
  import Header from "$lib/components/shell/Header.svelte";
  import Footer from "$lib/components/shell/Footer.svelte";
  import GuideContent from "$lib/components/mado/GuideContent.svelte";

  let { data }: { data: PageData } = $props();
</script>

<svelte:head><title>使い方 | Mado</title></svelte:head>

<div class="flex flex-col min-h-dvh">
  <Header session={data.session} />
  <main class="flex-1"><GuideContent /></main>
  <Footer />
</div>

// app/guide/page.tsx
import type { Metadata } from "next";
import { Header } from "@/components/shell/header";
import { Footer } from "@/components/shell/footer";
import { GuideContent } from "@/components/mado/guide-content";

export const metadata: Metadata = { title: "使い方" };

export default function GuidePage() {
  return (
    <div className="flex flex-col min-h-dvh">
      <Header />
      <main className="flex-1">
        <GuideContent />
      </main>
      <Footer />
    </div>
  );
}
