// app/about/page.tsx
import type { Metadata } from "next";
import { Header } from "@/components/shell/header";
import { Footer } from "@/components/shell/footer";
import { AboutContent } from "@/components/mado/about-content";

export const metadata: Metadata = { title: "Madoについて" };

export default function AboutPage() {
  return (
    <div className="flex flex-col min-h-dvh">
      <Header />
      <main className="flex-1">
        <AboutContent />
      </main>
      <Footer />
    </div>
  );
}

// src/routes/about/+page.svelte
<script lang="ts">
  import type { PageData } from "./$types";
  import Header from "$lib/components/shell/Header.svelte";
  import Footer from "$lib/components/shell/Footer.svelte";
  import AboutContent from "$lib/components/mado/AboutContent.svelte";

  let { data }: { data: PageData } = $props();
</script>

<svelte:head><title>Madoについて | Mado</title></svelte:head>

<div class="flex flex-col min-h-dvh">
  <Header session={data.session} />
  <main class="flex-1"><AboutContent /></main>
  <Footer />
</div>
